name: rc_companion
description: "Application de suivi des modèles RC et batteries."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  supabase_flutter: ^2.16.0
  image_picker: ^1.2.1
  pdf: ^3.11.3
  printing: ^5.14.2

  # Sélection des notices et vues éclatées en PDF
  file_picker: ^11.0.2

  # Affichage des PDF directement dans RC Companion
  pdfrx: ^2.4.7
  mobile_scanner: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true